# Generated by Django 4.0.6 on 2022-09-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_i_m_img_alter_projects_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i_m',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='icons',
            field=models.ImageField(upload_to='icons-1'),
        ),
    ]
