# Generated by Django 4.0.6 on 2022-09-13 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_i_m_img_alter_projects_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='i_m',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.i_m'),
            preserve_default=False,
        ),
    ]
